import { User } from "@/services/auth/LoginResponse";

type NotificationsTypes =
  | "NOTIFICATIONS_ACCOUNT_ACCOUNT_CHANGES"
  | "NOTIFICATIONS_ACCOUNT_SECURITY_ALERTS"
  | "NOTIFICATIONS_ACCOUNT_SUBSCRIPTION_CHANGES"
  | "NOTIFICATIONS_MARKETING_SPECIAL_OFFERS"
  | "NOTIFICATIONS_MARKETING_NEWSLETTER"
  | "NOTIFICATIONS_MARKETING_EVENT_INVITATIONS"
  | "NOTIFICATIONS_BILLING_UPCOMING_PAYMENTS"
  | "NOTIFICATIONS_BILLING_PAYMENT_FAILURES"
  | "NOTIFICATIONS_BILLING_PAYMENT_CONFIRMATIONS";

interface NotificationProps {
  user: User;
  onUpdate: (type: NotificationsTypes, value: string | boolean) => void;
}
